### ISSUE TITLE
Error with IOS devices.

### ISSUE THREAD

**Issue by jchristopher327** [jfilliben/dns-crawl#1]
The script completes when running agaisnt nxos devices but I get the following error when the device is IOS. I thought it was due to the output of `show ip int brief` in IOS has interfaces with no IP addresses so I edited the command being sent from `show ip int brief` to `sh ip int brief | i [1-9]\.` This didn't work either.

`Traceback (most recent call last):
  File "dns-crawl.py", line 440, in <module>
    main()
  File "dns-crawl.py", line 427, in main
    dnsDict = create_dns_dict(interfacesDict)
  File "dns-crawl.py", line 387, in create_dns_dict
    interface_name = interface_identifier(interface_string)
  File "dns-crawl.py", line 143, in interface_identifier
    if global_verbose: print "UNKNOWN INT TYPE ==" + intType
NameError: global name 'global_verbose' is not defined`

**Comment by jchristopher327** [comment]
Found that the issue was because the IOS devices had FortyGig interfaces and updated the script to handle `Fo` output.
